### ISSUE TITLE
안녕하세요 :)

### ISSUE THREAD

**Issue by joonas-yoon** [futurers/BOJ-App#14]
어떤 내용인지 확인해보다 여기까지 왔네요.

Electron으로 다시 빌드하시는거라면, Boj extended 코드가 업데이트 될 수도 있으니 서브모듈로 관리해보시는건 어떠세요?

git submodule : https://git-scm.com/book/ko/v2/Git-%EB%8F%84%EA%B5%AC-%EC%84%9C%EB%B8%8C%EB%AA%A8%EB%93%88

`joonas-yoon/boj-extended` 레포지토리의 `release` 브랜치랑 연결하시면, 업데이트된 코드를 바로 가져오실 수 있을거에요.

example of `.gitmodules`:
```
[submodule "BOJExtended"]
        path = BOJExtended
        url = https://github.com/joonas-yoon/boj-extended
        branch = release
```

**Comment by smartwe** [comment]
아!
저도 몰랐던 기능이네용
한번 써봐야겠네요

**Comment by smartwe** [comment]
서브모듈이 적용이 잘 안되네요ㅜㅜ

**Comment by smartwe** [comment]
그리고 release 브랜치의 확장프로그램 버전이 1.7인걸로 보아 main 브랜치가 더 맞아보이네요

**Comment by joonas-yoon** [comment]
오 마침 #15 에서 main 브랜치를 서브모듈로 추가했어요

**Comment by smartwe** [comment]
어떻게 하셨징

**Comment by smartwe** [comment]
ㄷㄷ 확인해보고 머지할께요!

**Comment by joonas-yoon** [comment]
GitHub 인터페이스에서는 안되는것 같고, 터미널에서 그냥 이렇게 실행했어요

```
git submodule add https://github.com/joonas-yoon/boj-extended
```

지금 보니까 폴더명도 바꿀 수 있었네요

**Comment by smartwe** [comment]
아그리고 release 브랜치가 1.7버전인데 맞나요?

**Comment by joonas-yoon** [comment]
음 `1.7.5.2` 버전이긴 하네요 왜지..

저 브랜치는 사실 기록용 + DB 업데이트용이고, 실제 배포는 main에서 하고 있기는 해요 ㅋㅋ..

**Comment by smartwe** [comment]
그럼 main으로 해주실수 있을까요 ㅎㅎ

**Comment by joonas-yoon** [comment]
> 오 마침 #15 에서 main 브랜치를 서브모듈로 추가했어요

`main` 입니다!

**Comment by smartwe** [comment]
타이밍이 기가 막히네욥

**Comment by smartwe** [comment]
머지 완료

**Comment by smartwe** [comment]
@joonas-yoon 혹시 이메일 말씀해주실수있을까요?
개인적으로 할말이 있어서요

**Comment by joonas-yoon** [comment]
제 깃헙 프로필에서 뱃지들 보시면 Gmail 버튼이 있어요. 그거 클릭하시면 메일로 연결됩니당

**Comment by smartwe** [comment]
오 저도 마침 찾았어요 :)
